// Regenerates the bundled seed registry snapshot (docs/03 §1.2): the
// offline bootstrap used on a cold start with no network. Run before each
// FlutterX release (docs/08 §7 pipeline step 5):
//
//   dart run tool/regenerate_seed.dart
//
// Fetches releases_<os>.json for all three OSes and embeds a trimmed
// subset (recent stable + beta entries that carry a Dart mapping) into
// packages/flutterx_registry/lib/src/seed_snapshot.g.dart.

import 'dart:convert';
import 'dart:io';

const _baseUrl =
    'https://storage.googleapis.com/flutter_infra_release/releases';
const _outPath = 'packages/flutterx_registry/lib/src/seed_snapshot.g.dart';
const _keepStable = 40; // distinct stable versions to keep
const _keepBeta = 15; //  distinct beta versions to keep

Future<void> main() async {
  final http = HttpClient();
  final perOs = <String, String>{};

  for (final os in ['macos', 'linux', 'windows']) {
    final url = Uri.parse('$_baseUrl/releases_$os.json');
    stdout.writeln('fetching $url …');
    final request = await http.getUrl(url);
    final response = await request.close();
    if (response.statusCode != 200) {
      stderr.writeln('HTTP ${response.statusCode} for $url');
      exitCode = 1;
      return;
    }
    final root =
        jsonDecode(await response.transform(utf8.decoder).join())
            as Map<String, Object?>;
    perOs[os] = jsonEncode({
      'base_url': root['base_url'],
      'releases': _trim(root['releases']! as List<Object?>),
    });
  }
  http.close();

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/regenerate_seed.dart — do not edit.')
    ..writeln('// Bundled seed registry snapshot (docs/03 §1.2).')
    ..writeln()
    ..writeln('/// When the seed data was captured from the live index.')
    ..writeln(
      'final DateTime seedGeneratedAt = '
      'DateTime.parse(${_dartString(DateTime.now().toUtc().toIso8601String())});',
    )
    ..writeln()
    ..writeln('/// Raw trimmed `releases_<os>.json` bodies, keyed by')
    ..writeln('/// `TargetOs.name`.')
    ..writeln('const Map<String, String> seedReleaseIndexes = {');
  for (final entry in perOs.entries) {
    buffer.writeln('  ${_dartString(entry.key)}: ${_dartString(entry.value)},');
  }
  buffer.writeln('};');

  File(_outPath).writeAsStringSync(buffer.toString());
  stdout.writeln('wrote $_outPath (${File(_outPath).lengthSync()} bytes)');
}

/// Keeps the newest N distinct versions per kept channel, all arch
/// variants, only entries with a Dart mapping.
List<Map<String, Object?>> _trim(List<Object?> releases) {
  final kept = <Map<String, Object?>>[];
  final seenPerChannel = <String, Set<String>>{'stable': {}, 'beta': {}};
  final limits = {'stable': _keepStable, 'beta': _keepBeta};

  for (final raw in releases) {
    final entry = (raw! as Map<String, Object?>);
    final channel = entry['channel'] as String?;
    final seen = seenPerChannel[channel];
    if (seen == null) continue; // dev/master never seed
    if (entry['dart_sdk_version'] == null) continue;
    final version = entry['version']! as String;
    if (!seen.contains(version) && seen.length >= limits[channel]!) continue;
    seen.add(version);
    kept.add(entry);
  }
  return kept;
}

String _dartString(String value) =>
    "'${value.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
