import 'dart:io';

import 'package:flutterx_domain/flutterx_domain.dart';
import 'package:flutterx_storage/src/artifact_store.dart' show CreateLink;
import 'package:flutterx_storage/src/store_layout.dart';
import 'package:flutterx_storage/src/store_lock.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// The evidence files collected for the Scanner, by project-root-relative
/// path (docs/03 §2.1 sources 1–9).
const _evidenceFileNames = [
  '.flutterx/resolution.lock',
  'flutterx.yaml',
  '.fvmrc',
  '.fvm/fvm_config.json',
  '.puro.json',
  'pubspec.yaml',
  'pubspec.lock',
  '.metadata',
  'codemagic.yaml',
];

/// [ProjectStore] over the filesystem (docs/06 §6): evidence collection,
/// the resolution lockfile, and the project SDK link + registry.
final class FileProjectStore implements ProjectStore {
  FileProjectStore({
    required this.layout,
    required this.lock,
    required this.createLink,
  });

  final StoreLayout layout;
  final StoreLock lock;
  final CreateLink createLink;

  @override
  Future<Project?> findProject(String startDir) async {
    var dir = Directory(startDir).absolute;
    while (true) {
      if (File(p.join(dir.path, 'pubspec.yaml')).existsSync() ||
          File(p.join(dir.path, 'flutterx.yaml')).existsSync()) {
        return Project(rootPath: dir.path);
      }
      final parent = dir.parent;
      if (parent.path == dir.path) return null;
      dir = parent;
    }
  }

  @override
  Future<Result<void>> writePin(
    Project project, {
    String? pinVersion,
    String? policyChannel,
  }) async {
    assert(
      (pinVersion == null) != (policyChannel == null),
      'exactly one of pin or policy',
    );
    final file = File(p.join(project.rootPath, 'flutterx.yaml'));
    final buffer = StringBuffer()
      ..writeln('# FlutterX project intent — hand-editable (docs/04 §4).')
      ..writeln(
        pinVersion != null ? 'flutter: $pinVersion' : 'policy: $policyChannel',
      );
    await file.writeAsString(buffer.toString());
    return const Result.ok(null);
  }

  @override
  Future<EvidenceFiles> readEvidence(Project project) async {
    final files = <String, String>{};
    for (final name in _evidenceFileNames) {
      final file = File(p.join(project.rootPath, name));
      if (file.existsSync()) {
        files[name] = await file.readAsString();
      }
    }
    // CI workflows: every YAML under .github/workflows (docs/03 §2.1 #9).
    final workflows = Directory(
      p.join(project.rootPath, '.github', 'workflows'),
    );
    if (workflows.existsSync()) {
      await for (final entry in workflows.list()) {
        if (entry is File &&
            (entry.path.endsWith('.yml') || entry.path.endsWith('.yaml'))) {
          final relative = p
              .relative(entry.path, from: project.rootPath)
              .replaceAll(r'\', '/');
          files[relative] = await entry.readAsString();
        }
      }
    }
    return EvidenceFiles(files: files);
  }

  @override
  Future<Resolution?> readLock(Project project) async {
    final file = File(p.join(project.rootPath, '.flutterx/resolution.lock'));
    if (!file.existsSync()) return null;
    try {
      final yaml = loadYaml(await file.readAsString()) as YamlMap;
      final flutter = yaml['flutter'].toString();
      return Resolution(
        // Reconstructed from the lock alone: enough for the fast path
        // (shims, current); full release data comes from the registry.
        chosen: FlutterRelease(
          version: SemVer.parse(flutter),
          channel:
              Channel.tryParse(yaml['channel'].toString()) ?? Channel.stable,
          gitTag: flutter,
          frameworkSha: '',
          dartVersion: SemVer.parse(yaml['dart'].toString()),
          releasedAt: DateTime.fromMillisecondsSinceEpoch(0, isUtc: true),
          artifacts: const {},
        ),
        confidence: Confidence.high,
        reasons: [
          for (final reason in (yaml['reasons'] as YamlList? ?? YamlList()))
            Reason(text: reason.toString()),
        ],
        evidenceHash: yaml['evidenceHash']?.toString() ?? '',
        resolvedBy: ResolvedBy.values.firstWhere(
          (v) => v.name == yaml['resolvedBy'].toString(),
          orElse: () => ResolvedBy.use,
        ),
        resolvedAt: DateTime.parse(yaml['resolvedAt'].toString()),
      );
    } on Exception {
      return null; // corrupt lock → treated as unresolved; doctor flags it
    }
  }

  @override
  Future<Result<void>> writeLock(Project project, Resolution resolution) async {
    final file = File(p.join(project.rootPath, '.flutterx/resolution.lock'));
    await file.parent.create(recursive: true);
    // Exactly the documented format (docs/03 §7) — this file is a public
    // contract and is committed to the project's repository.
    final buffer = StringBuffer()
      ..writeln(
        '# .flutterx/resolution.lock — generated by flutterx; '
        'commit this file.',
      )
      ..writeln('flutterx: 1')
      ..writeln('flutter: ${resolution.chosen.version}')
      ..writeln('dart: ${resolution.chosen.dartVersion}')
      ..writeln('channel: ${resolution.chosen.channel.name}')
      ..writeln(
        'resolvedAt: ${resolution.resolvedAt.toUtc().toIso8601String()}',
      )
      ..writeln('resolvedBy: ${resolution.resolvedBy.name}')
      ..writeln('evidenceHash: ${resolution.evidenceHash}')
      ..writeln('reasons:');
    for (final reason in resolution.reasons) {
      buffer.writeln('  - "${reason.text.replaceAll('"', r'\"')}"');
    }
    await file.writeAsString(buffer.toString());
    return const Result.ok(null);
  }

  @override
  Future<Result<void>> linkSdk(Project project, InstalledSdk sdk) {
    return lock.withExclusive(() async {
      final linkPath = p.join(project.rootPath, '.flutterx', 'sdk');
      await Directory(p.dirname(linkPath)).create(recursive: true);
      final existing = Link(linkPath);
      if (existing.existsSync()) await existing.delete();
      final linked = await createLink(targetPath: sdk.path, linkPath: linkPath);
      if (linked case Err(:final failure)) return Result.err(failure);

      // Register for GC reference counting (docs/05 §6.1).
      final state = await layout.loadState();
      if (state case Err(:final failure)) return Result.err(failure);
      await layout.saveState(
        state.valueOrNull!.withProject(
          ProjectRef(
            path: project.rootPath,
            version: sdk.release.version.toString(),
          ),
        ),
      );
      return const Result.ok(null);
    });
  }
}
